---
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: amacleod
      url-base: https://github.com/amacleod
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zaphod-config
      remote: amacleod
      revision: main
    - name: weejock-zmk
      remote: amacleod
      revision: main
  self:
    path: config
